name: Build PyBroma
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: macOS
            os: macos-latest
          - name: Linux
            os: ubuntu-latest
        python-version: ["3.10"]

    name: Build ${{ matrix.config.name }} for ${{ matrix.python-version }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install scikit-build cython wheel cmake ninja

      - name: Build
        run: pip wheel . --no-deps --wheel-dir dist

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: pybroma-${{ matrix.config.name }}-${{ matrix.python-version }}
          path: dist/*.whl